### ISSUE TITLE
An error occurred during function

### ISSUE THREAD

**Issue by luis-rt** [docwho2/java-connect-lex-chatgpt#36]
When deploying, I am encountering the following error:

Resource handler returned message: "Resource of type 'AWS::Lambda::Version' with identifier 'arn:aws:lambda:us-west-2:543274669242:function:connect-chatgpt-ChatGPT:3' did not stabilize. Status Reason is An error occurred during function initialization." (RequestToken: dc471de3-75b5-4737-efc8-de9c60cbcc2b, HandlerErrorCode: NotStabilized)

I have tried to look for information, but it has not been satisfactory.

Do you have any advice?

 
<img width="1425" alt="Captura de pantalla 2023-12-06 a la(s) 12 22 25" src="https://github.com/docwho2/java-connect-lex-chatgpt/assets/25042698/1bd373e0-dc1c-4d44-b198-b3e464b7ee5c">

**Comment by docwho2** [comment]
would need to see the error from the log file in CloudWatch for ChatGPT lambda (/aws/lambda/connect-chatgpt-ChatGPT)

Link for you should be:

https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fconnect-chatgpt-ChatGPT

I ran clean with the default stack and did not observe any errors

Waiting for changeset to be created..

CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                                        LogicalResourceId                                                ResourceType                                                     Replacement                                                    
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                                            BotAlias                                                         AWS::Lex::BotAlias                                               N/A                                                            
+ Add                                                            BotRuntimeRole                                                   AWS::IAM::Role                                                   N/A                                                            
+ Add                                                            BotVersion                                                       AWS::Lex::BotVersion                                             N/A                                                            
+ Add                                                            BucketKey                                                        AWS::KMS::Key                                                    N/A                                                            
+ Add                                                            BucketPolicy                                                     AWS::S3::BucketPolicy                                            N/A                                                            
+ Add                                                            CallTable                                                        AWS::DynamoDB::Table                                             N/A                                                            
+ Add                                                            ChatGPTAliasSNAPSTART                                            AWS::Lambda::Alias                                               N/A                                                            
+ Add                                                            ChatGPTLogGroup                                                  AWS::Logs::LogGroup                                              N/A                                                            
+ Add                                                            ChatGPTRole                                                      AWS::IAM::Role                                                   N/A                                                            
+ Add                                                            ChatGPTVersion1ed983eeb7                                         AWS::Lambda::Version                                             N/A                                                            
+ Add                                                            ChatGPT                                                          AWS::Lambda::Function                                            N/A                                                            
+ Add                                                            ClosingPromptEnglish                                             Custom::PromptCreator                                            N/A                                                            
+ Add                                                            ClosingPromptSpanish                                             Custom::PromptCreator                                            N/A                                                            
+ Add                                                            ConnectFlow                                                      AWS::Connect::ContactFlow                                        N/A                                                            
+ Add                                                            ContactUpdatePolicy                                              AWS::IAM::ManagedPolicy                                          N/A                                                            
+ Add                                                            ErrorPromptEnglish                                               Custom::PromptCreator                                            N/A                                                            
+ Add                                                            ErrorPromptSpanish                                               Custom::PromptCreator                                            N/A                                                            
+ Add                                                            HelpPromptEnglish                                                Custom::PromptCreator                                            N/A                                                            
+ Add                                                            HelpPromptSpanish                                                Custom::PromptCreator                                            N/A                                                            
+ Add                                                            LexBot                                                           AWS::Lex::Bot                                                    N/A                                                            
+ Add                                                            LexPromptEnglish                                                 Custom::PromptCreator                                            N/A                                                            
+ Add                                                            LexPromptSpanish                                                 Custom::PromptCreator                                            N/A                                                            
+ Add                                                            LexToChatGPTPerm                                                 AWS::Lambda::Permission                                          N/A                                                            
+ Add                                                            LexToChatGPTSnapPerm                                             AWS::Lambda::Permission                                          N/A                                                            
+ Add                                                            LexV2ConnectIntegration                                          AWS::Connect::IntegrationAssociation                             N/A                                                            
+ Add                                                            MainPrompt                                                       Custom::PromptCreator                                            N/A                                                            
+ Add                                                            NewCallLookupAliasSNAPSTART                                      AWS::Lambda::Alias                                               N/A                                                            
+ Add                                                            NewCallLookupLogGroup                                            AWS::Logs::LogGroup                                              N/A                                                            
+ Add                                                            NewCallLookupRole                                                AWS::IAM::Role                                                   N/A                                                            
+ Add                                                            NewCallLookupSNSTriggerPermission                                AWS::Lambda::Permission                                          N/A                                                            
+ Add                                                            NewCallLookupSNSTrigger                                          AWS::SNS::Subscription                                           N/A                                                            
+ Add                                                            NewCallLookupVersion4d671ca6e7                                   AWS::Lambda::Version                                             N/A                                                            
+ Add                                                            NewCallLookup                                                    AWS::Lambda::Function                                            N/A                                                            
+ Add                                                            NewCallTopic                                                     AWS::SNS::Topic                                                  N/A                                                            
+ Add                                                            PromptBucket                                                     AWS::S3::Bucket                                                  N/A                                                            
+ Add                                                            PromptCreatorLogGroup                                            AWS::Logs::LogGroup                                              N/A                                                            
+ Add                                                            PromptCreatorRole                                                AWS::IAM::Role                                                   N/A                                                            
+ Add                                                            PromptCreator                                                    AWS::Lambda::Function                                            N/A                                                            
+ Add                                                            SendToSNSConnectIntegration                                      AWS::Connect::IntegrationAssociation                             N/A                                                            
+ Add                                                            SendToSNSLogGroup                                                AWS::Logs::LogGroup                                              N/A                                                            
+ Add                                                            SendToSNSRole                                                    AWS::IAM::Role                                                   N/A                                                            
+ Add                                                            SendToSNS                                                        AWS::Lambda::Function                                            N/A                                                            
+ Add                                                            SessionTable                                                     AWS::DynamoDB::Table                                             N/A                                                            
+ Add                                                            SpanishPrompt                                                    Custom::PromptCreator                                            N/A                                                            
+ Add                                                            TransferPromptEnglish                                            Custom::PromptCreator                                            N/A                                                            
+ Add                                                            TransferPromptSpanish                                            Custom::PromptCreator                                            N/A                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Changeset created successfully. arn:aws:cloudformation:us-east-1:*:changeSet/samcli-deploy1701919920/547de7e7-bac2-4dc3-9d20-ce18e433021e


2023-12-06 21:32:27 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 5.0 seconds)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                                   ResourceType                                                     LogicalResourceId                                                ResourceStatusReason                                           
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                                               AWS::CloudFormation::Stack                                       connect-chatgpt                                                  User Initiated                                                 
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              ChatGPTLogGroup                                                  -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   BotRuntimeRole                                                   -                                                              
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              PromptCreatorLogGroup                                            -                                                              
CREATE_IN_PROGRESS                                               AWS::KMS::Key                                                    BucketKey                                                        -                                                              
CREATE_IN_PROGRESS                                               AWS::DynamoDB::Table                                             SessionTable                                                     -                                                              
CREATE_IN_PROGRESS                                               AWS::DynamoDB::Table                                             CallTable                                                        -                                                              
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              NewCallLookupLogGroup                                            -                                                              
CREATE_IN_PROGRESS                                               AWS::SNS::Topic                                                  NewCallTopic                                                     -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::ManagedPolicy                                          ContactUpdatePolicy                                              -                                                              
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              PromptCreatorLogGroup                                            Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              ChatGPTLogGroup                                                  Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::IAM::ManagedPolicy                                          ContactUpdatePolicy                                              Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::SNS::Topic                                                  NewCallTopic                                                     Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   BotRuntimeRole                                                   Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::DynamoDB::Table                                             SessionTable                                                     Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::KMS::Key                                                    BucketKey                                                        Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              NewCallLookupLogGroup                                            Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Logs::LogGroup                                              PromptCreatorLogGroup                                            -                                                              
CREATE_COMPLETE                                                  AWS::Logs::LogGroup                                              ChatGPTLogGroup                                                  -                                                              
CREATE_IN_PROGRESS                                               AWS::DynamoDB::Table                                             CallTable                                                        Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::SNS::Topic                                                  NewCallTopic                                                     -                                                              
CREATE_COMPLETE                                                  AWS::Logs::LogGroup                                              NewCallLookupLogGroup                                            -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   SendToSNSRole                                                    -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   SendToSNSRole                                                    Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::DynamoDB::Table                                             SessionTable                                                     -                                                              
CREATE_COMPLETE                                                  AWS::DynamoDB::Table                                             CallTable                                                        -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   ChatGPTRole                                                      -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   ChatGPTRole                                                      Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::IAM::ManagedPolicy                                          ContactUpdatePolicy                                              -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   NewCallLookupRole                                                -                                                              
CREATE_COMPLETE                                                  AWS::IAM::Role                                                   BotRuntimeRole                                                   -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   NewCallLookupRole                                                Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Lex::Bot                                                    LexBot                                                           -                                                              
CREATE_COMPLETE                                                  AWS::IAM::Role                                                   SendToSNSRole                                                    -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            SendToSNS                                                        -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            SendToSNS                                                        Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Lex::Bot                                                    LexBot                                                           Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Function                                            SendToSNS                                                        -                                                              
CREATE_COMPLETE                                                  AWS::IAM::Role                                                   ChatGPTRole                                                      -                                                              
CREATE_IN_PROGRESS                                               AWS::Connect::IntegrationAssociation                             SendToSNSConnectIntegration                                      -                                                              
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              SendToSNSLogGroup                                                -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            ChatGPT                                                          -                                                              
CREATE_IN_PROGRESS                                               AWS::Connect::IntegrationAssociation                             SendToSNSConnectIntegration                                      Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Logs::LogGroup                                              SendToSNSLogGroup                                                Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Connect::IntegrationAssociation                             SendToSNSConnectIntegration                                      -                                                              
CREATE_COMPLETE                                                  AWS::Logs::LogGroup                                              SendToSNSLogGroup                                                -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            ChatGPT                                                          Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::IAM::Role                                                   NewCallLookupRole                                                -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            NewCallLookup                                                    -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            NewCallLookup                                                    Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Function                                            ChatGPT                                                          -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          LexToChatGPTPerm                                                 -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Version                                             ChatGPTVersion1ed983eeb7                                         -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          LexToChatGPTPerm                                                 Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Permission                                          LexToChatGPTPerm                                                 -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Version                                             ChatGPTVersion1ed983eeb7                                         Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Function                                            NewCallLookup                                                    -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Version                                             NewCallLookupVersion4d671ca6e7                                   -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Version                                             NewCallLookupVersion4d671ca6e7                                   Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lex::Bot                                                    LexBot                                                           -                                                              
CREATE_IN_PROGRESS                                               AWS::Lex::BotVersion                                             BotVersion                                                       -                                                              
CREATE_IN_PROGRESS                                               AWS::Lex::BotVersion                                             BotVersion                                                       Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::KMS::Key                                                    BucketKey                                                        -                                                              
CREATE_IN_PROGRESS                                               AWS::S3::Bucket                                                  PromptBucket                                                     -                                                              
CREATE_IN_PROGRESS                                               AWS::S3::Bucket                                                  PromptBucket                                                     Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lex::BotVersion                                             BotVersion                                                       -                                                              
CREATE_COMPLETE                                                  AWS::S3::Bucket                                                  PromptBucket                                                     -                                                              
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   PromptCreatorRole                                                -                                                              
CREATE_IN_PROGRESS                                               AWS::S3::BucketPolicy                                            BucketPolicy                                                     -                                                              
CREATE_IN_PROGRESS                                               AWS::S3::BucketPolicy                                            BucketPolicy                                                     Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::IAM::Role                                                   PromptCreatorRole                                                Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::S3::BucketPolicy                                            BucketPolicy                                                     -                                                              
CREATE_COMPLETE                                                  AWS::IAM::Role                                                   PromptCreatorRole                                                -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            PromptCreator                                                    -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Function                                            PromptCreator                                                    Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Function                                            PromptCreator                                                    -                                                              
CREATE_COMPLETE                                                  AWS::Lambda::Version                                             ChatGPTVersion1ed983eeb7                                         -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            LexPromptSpanish                                                 -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            LexPromptEnglish                                                 -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ClosingPromptEnglish                                             -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ErrorPromptEnglish                                               -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ClosingPromptSpanish                                             -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            TransferPromptEnglish                                            -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            TransferPromptSpanish                                            -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            HelpPromptEnglish                                                -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            MainPrompt                                                       -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            HelpPromptSpanish                                                -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            SpanishPrompt                                                    -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ErrorPromptSpanish                                               -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Alias                                               ChatGPTAliasSNAPSTART                                            -                                                              
CREATE_COMPLETE                                                  AWS::Lambda::Version                                             NewCallLookupVersion4d671ca6e7                                   -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Alias                                               ChatGPTAliasSNAPSTART                                            Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Alias                                               ChatGPTAliasSNAPSTART                                            -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          LexToChatGPTSnapPerm                                             -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Alias                                               NewCallLookupAliasSNAPSTART                                      -                                                              
CREATE_IN_PROGRESS                                               AWS::Lex::BotAlias                                               BotAlias                                                         -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Alias                                               NewCallLookupAliasSNAPSTART                                      Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Lambda::Alias                                               NewCallLookupAliasSNAPSTART                                      -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          LexToChatGPTSnapPerm                                             Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::SNS::Subscription                                           NewCallLookupSNSTrigger                                          -                                                              
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          NewCallLookupSNSTriggerPermission                                -                                                              
CREATE_COMPLETE                                                  AWS::Lambda::Permission                                          LexToChatGPTSnapPerm                                             -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            LexPromptSpanish                                                 Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Lex::BotAlias                                               BotAlias                                                         Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            SpanishPrompt                                                    Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            HelpPromptSpanish                                                Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ErrorPromptSpanish                                               Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            MainPrompt                                                       Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            TransferPromptSpanish                                            Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ErrorPromptEnglish                                               Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            LexPromptSpanish                                                 -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            HelpPromptEnglish                                                Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            SpanishPrompt                                                    -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ClosingPromptEnglish                                             Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            HelpPromptSpanish                                                -                                                              
CREATE_COMPLETE                                                  AWS::Lex::BotAlias                                               BotAlias                                                         -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            MainPrompt                                                       -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            LexPromptEnglish                                                 Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            ErrorPromptSpanish                                               -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            TransferPromptSpanish                                            -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            ErrorPromptEnglish                                               -                                                              
CREATE_IN_PROGRESS                                               AWS::SNS::Subscription                                           NewCallLookupSNSTrigger                                          Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            HelpPromptEnglish                                                -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            ClosingPromptEnglish                                             -                                                              
CREATE_COMPLETE                                                  AWS::SNS::Subscription                                           NewCallLookupSNSTrigger                                          -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            LexPromptEnglish                                                 -                                                              
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            ClosingPromptSpanish                                             Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Lambda::Permission                                          NewCallLookupSNSTriggerPermission                                Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               Custom::PromptCreator                                            TransferPromptEnglish                                            Resource creation Initiated                                    
CREATE_COMPLETE                                                  Custom::PromptCreator                                            ClosingPromptSpanish                                             -                                                              
CREATE_IN_PROGRESS                                               AWS::Connect::IntegrationAssociation                             LexV2ConnectIntegration                                          -                                                              
CREATE_IN_PROGRESS                                               AWS::Connect::ContactFlow                                        ConnectFlow                                                      -                                                              
CREATE_COMPLETE                                                  AWS::Lambda::Permission                                          NewCallLookupSNSTriggerPermission                                -                                                              
CREATE_COMPLETE                                                  Custom::PromptCreator                                            TransferPromptEnglish                                            -                                                              
CREATE_IN_PROGRESS                                               AWS::Connect::ContactFlow                                        ConnectFlow                                                      Resource creation Initiated                                    
CREATE_IN_PROGRESS                                               AWS::Connect::IntegrationAssociation                             LexV2ConnectIntegration                                          Resource creation Initiated                                    
CREATE_COMPLETE                                                  AWS::Connect::IntegrationAssociation                             LexV2ConnectIntegration                                          -                                                              
CREATE_COMPLETE                                                  AWS::Connect::ContactFlow                                        ConnectFlow                                                      -                                                              
CREATE_COMPLETE                                                  AWS::CloudFormation::Stack                                       connect-chatgpt                                                  -                                                              
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Successfully created/updated stack - connect-chatgpt in us-east-1
